# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 注意缺陷障碍 博客
email:  surfree.us@gmail.com
description: > # 多动症信息博客"baseurl:" # 写一个网站的介绍，这个在head meta 里面出现(为了google的搜索) 而且在feed.xml 网站介绍里面
  注意缺陷障碍 信息博客

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adhd.diaosi.club" # the base hostname & protocol for your site

social_links: [

]
# Build settings
highlighter: pygments
# encoding: utf-8
excerpt_separator: ""

# paginate: 5
